image: debian/stable
arch: amd64
packages:
  - build-essential
  - gcc-multilib
  - clang
  - tcc
sources:
  - https://git.sr.ht/~ashn/sunder
tasks:
  - c99-debug: |
      cd sunder
      make clean check examples CFLAGS='$(C99_DBG)'
  - c99-release: |
      cd sunder
      make clean check examples CFLAGS='$(C99_REL)'
  - c99-release-backend-clang: |
      cd sunder
      make clean check examples CFLAGS='$(C99_REL)' SUNDER_DEFAULT_CC=clang
  - c99-release-backend-gcc: |
      cd sunder
      make clean check examples CFLAGS='$(C99_REL)' SUNDER_DEFAULT_CC=gcc
  - clang-debug: |
      cd sunder
      make clean check examples CC=clang CFLAGS='$(GNU_DBG)'
  - clang-release: |
      cd sunder
      make clean check examples CC=clang CFLAGS='$(GNU_REL)'
  - clang-release-x86-sunder-compile: |
      cd sunder
      make clean check examples CC=clang CFLAGS='$(GNU_REL) -m32'
  - gcc-debug: |
      cd sunder
      make clean check examples CC=gcc CFLAGS='$(GNU_DBG)'
  - gcc-release: |
      cd sunder
      make clean check examples CC=gcc CFLAGS='$(GNU_REL)'
  - gcc-release-x86-sunder-compile: |
      cd sunder
      make clean check examples CC=gcc CFLAGS='$(GNU_REL) -m32'
  - tcc-debug: |
      cd sunder
      SUNDER_CC=tcc make clean check examples CC=tcc CFLAGS='$(C99_DBG)'
  - tcc-release: |
      cd sunder
      SUNDER_CC=tcc make clean check examples CC=tcc CFLAGS='$(C99_REL)'
triggers:
  - action: email
    condition: failure
    to: "<me@ashn.dev>"
